---
title: "Data Management"
output: html_document
---
#### Sarah McCutcheon and Juliana Matos 
###Types of Data

Provide a description of the data you will collect or re-use, including the file types, dataset size, number of expected files or sets, and content. Data types could include text, spreadsheets, images, 3D models, software, audio files, video files, reports, surveys, patient records, etc. Data that underlie the findings reported in a journal article or conference paper should be deposited in accordance with the policies of the publication and according to the procedures laid out in the DMP included in the proposal that led to the award on which the research is based. 

Consider the following:

* What data will be generated in the research?
    + Through this study, researchers will create a ranking of cities that are most likely to implement a program similar to Santa Barbara's Wildland Fire Suppression Assessment District. 
* What data types will you be creating or capturing?
    + Data captured during this study includes GIS layer data on fire frequency in California, WUI index, topography (DEM), vegetation type, and census information.  Final data of top ranking cities will be in the form of city polygons. 
* How will you capture or create the data?
    + All data layers will be edited to reflect the same geographic projection system, resolution, and value (0 to 1).
* If you will be using existing data, state this and include how you will obtain it.
    + Data for California fire frequency, WUI index, and vegetation type existed prior to this study and was obtianed from CalFire. 
* What is the relationship between the data you are collecting and any existing data?
    + TBD
* How will the data be processed?
    + All data layers will be processed to reflect the same geographic projection system, resolution, and value (0 to 1).
* What quality assurance & quality control measures will you employ?
    + All ranking cities will be evaluated individually to assure that they have the required features. 

###Data and Metadata Standards
Datasets need metadata to be usable. Think about what details (metadata) someone else would need to be able to use these files. For example, you may need a readme.txt file to explain variables, structure of the files, etc. Consider the following:

* What contextual details (metadata) are needed to make the data you capture or collect meaningful?
    +  AHP Data
        - Metadata: 
    + Fire Frequency GIS Data
        - Metadata:
    + Vegetation Type
        - Metadata:
    + Topography:
        - Metadata
    + WUI Index
        - Metadata:
        
* What form will the metadata describing/documenting your data take?

* How will you create or capture these details?

* Which metadata standards will you use and why have you chosen them?

###Policies for Access and Sharing
Specify how you will share your data with others after the project is completed. Ideally, you will use an appropriate open-access discipline-specific data repository; regardless of the repository you choose, describe how you chose it. Consider these questions:

* How, when, and where will you make the data available?
    + We will make th edata available when the project is complete. Not later than July 2016.
* What resources will be needed to reuse the data? Examples include software or equipment.
    + RStudio and ArcGIS are needed to reuse the data.
* What is the process for gaining access to the data?
    + To gain access to the data, please contact Sarah MCutcheon (sarahmccutch@gmail.com) or     Juliana Matos (matosjuliana92@gmail.com).
* Who are the foreseeable data users?
    + Foreseeable data users are scientists looking to recreate our research for their own data needs.
* How should your data be cited?
    + Data shoudl be cited with the original source from the metadata, as well as an "accessed from", "contributed by", "collected by", etc. with DMP creators. 

###Policies and Provisions for Re-use, Re-distibution
Describe policies surrounding the re-use of your data – the EAR division is specifically interested in how soon you will make your data available. If you will not be making the data available for re-use immediately, explain why. Remember that EAR specifies that you must make your data available no later than two years after your research is complete. If there are other policy issues regarding data access and re-use (ethical or privacy issues, for instance) elaborate on them here. Consider these questions:

* When will you make the data available?
    + Data will be available once project is compelte, and no later than July 2016.
* Does the original data collector/creator/principal investigator retain the right to use the data before opening it up to wider use?
    + The data collector/creator/principal investigator retains the right to use the data before opening it up to wider use.
* Will any permission restrictions need to be placed on the data?
    + TBD
* How long will the original data collector/creator/principal investigator retain the right to use the data before making them available for wider distribution?
    + The original data collector/creator/principal investigator retain the right to use the data for five six months before making them available for wider distribution.
* Are there any embargo periods for political/commercial/patent reasons? If so, give details.
    + There are no embargo periods for political/commercial/patent reasons.
* Are there ethical and privacy issues? If so, how will these be resolved?
    + There are no ethical and privacy issues.
* What have you done to comply with your obligations in your IRB Protocol?
    + TBD
* Who will hold the intellectual property rights to the data and how might this affect data access?
    + Intellectual property rights to the data blongs to the original data source for all data layers. Weighting scores for layerss, obtained through AHP surveys, belongs to Juliana Matos and Sarah McCutcheon. 
* What and who are the intended or foreseeable uses / users of the data?
    + Various California city fire departments, city councils, and researchers may be foreseeable users of the data.  


###Plans for Archiving and Preservation of Access
Describe your long-term strategy for archiving and preserving your data. EAR encourages PIs to submit data to an “EAR-specified” repository. Consider the following:

* What is the long-term strategy for maintaining, curating and archiving the data?
    + 
* Which archive/repository/database have you identified as a place to deposit data?
    +
* What procedures does your intended long-term data storage facility have in place for preservation and backup?
    + 
* How long will/should data be kept beyond the life of the project?
    + 
* What data will be preserved for the long-term?
    + 
* What transformations will be necessary to prepare data for preservation / data sharing?
    + 
* What metadata/ documentation will be submitted alongside the data or created on deposit/ transformation in order to make the data reusable?
    +
* What related information will be deposited?
    +

## Data Question
# load libraries
library(readr)
library(dplyr)

# read in csv
surveys = FullData

# dplyr elegance
surveys %T>%                          # note tee operator %T>% for glimpse
  glimpse() %>%                       # view data
  select(fireRisk, years) %>%        # limit columns
  filter(fireRisk  == '5') %>%     # limit rows
  group_by(years) %>%                  # get count by first grouping
  summarize(n = n()) %>%              #   then summarize
  


